spring.application.name=cart
server.port=8081

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cart
spring.datasource.username=postgres
spring.datasource.password=roshin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true